<!DOCTYPE html>
<html lang="ru">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<?php if (!empty($seo_config["favicon"])) { ?>
<link href="<?php echo $seo_config["favicon"]; ?>" rel="shortcut icon">
<?php } ?>
<?php if (!empty($seo_config["title"])) { ?>
<title><?php echo $seo_config["title"]; ?></title>
<?php } ?>
<?php if (!empty($seo_config["meta_desc"])) { ?>
<meta name="description" content="<?php echo $seo_config["meta_desc"]; ?>" />
<?php } ?>
<?php if (!empty($seo_config["meta_keywords"])) { ?>
<meta name="keywords" content="<?php echo $seo_config["meta_keywords"]; ?>" />
<?php } ?>
<?php //$this->_connect_styles() ?>
<!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
<?php echo $content; ?>

<?php //$this->_connect_scripts() ?>
</body>
</html>
