<html>
<head>
    <meta content="text/html" charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Admin/view/css/style.css"/>
    <link rel="stylesheet" href="/Admin/view/css/style.makeup-modal.css"/>
    <link rel="stylesheet" href="/Admin/view/css/style.makeup-custom-modals.css"/>
    <link rel="stylesheet" href="/Admin/view/css/style.makeup-controls.css"/>

    <link rel="stylesheet" href="/public/css/autogen/style.css"/>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="/Admin/view/js/script.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
    <header class="makeup-header">
        <nav class="makeup-navigation clear-fix">
            <a class="makeup-button-back">
                <i class="fa fa-angle-left" aria-hidden="true"></i>
                <span class="title">Back</span>
            </a>
            <div class="control">
                <button class=""><i class="fa fa-floppy-o" aria-hidden="true"></i></button>
            </div>
        </nav>
    </header>

    <section class="makeup-designer clear-fix">
        <?php $blocks = $this->_getBlocks(); ?>
        <?php foreach ( $blocks as $key => $block ) { ?>
        <div class="makeup-block clear-fix" id="<?php echo $key; ?>">
            <div class="makeup-view" id="<?php echo $this->_getSuffix(); ?><?php echo $key; ?>">
                <?php echo $this->_getContent($block["name_pack"],$block["name_template"],$block["configuration"]); ?>
            </div>
            <div class="makeup-view-option">
                <button class="makeup-edit" name-pack="<?php echo $block["name_pack"]; ?>" id-section="<?php echo $key; ?>" name-template="<?php echo $block["name_template"]; ?>"><i class="fa fa-pencil fa-lg" aria-hidden="true"></i></button>
                <button class="makeup-option"><i class="fa fa-cog fa-lg" aria-hidden="true"></i></button>
                <button class="makeup-remove"><i class="fa fa-trash fa-lg" aria-hidden="true"></i></button>
                <button class="makeup-change-position"><i class="fa fa-align-justify fa-lg" aria-hidden="true"></i></button>

            </div>
        </div>

        <div class="makeup-add"><div class="makeup-add-button_area"><button class="makeup-add-button"><i class="fa fa-plus fa-lg" aria-hidden="true"></button></i></div></div>
        <?php } ?>
        <div class="makeup-modal option">
            <div class="makeup-modal-container">
            </div>
        </div>
        <div class="makeup-modal setting">
            <div class="makeup-modal-container">

            </div>
        </div>
        <div class="makeup-modal remove">
            <div class="makeup-modal-container">
                <div class="makeup-modal-title">
                    Удалить?
                </div>
                <div class="makeup-modal-body">
                    <div class="group_control">
                        <button>Да</button>
                        <button>Нет</button>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <footer class="footer">

    </footer>
</body>
</html>
