<html>
<head>
    <meta content="text/html" charset="utf-8">
    <title></title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.6.3/css/font-awesome.min.css">
    <link rel="stylesheet" href="/Admin/view/css/style.autogen.css"/>
    
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
</head>
<body>
    <div>
        <?php foreach ($head_block as $key => $classes) {?>
            <button
                class='btn btn-default'
                style="width: 40px; height: 40px; padding: 0px;"
                data-toggle="modal"
                data-target="#<?php echo $key; ?>"
            >
                <i class="fa <?php echo $classes->_get_setting_image(); ?> fa-2x" aria-hidden="true"></i>
            </button>
            <div id="<?php echo $key; ?>" class="modal fade" role="dialog">
                <div class="modal-dialog">

                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title"><?php echo $classes->_get_title(); ?></h4>
                        </div>
                        <div class="modal-body">
                            <?php $option = $classes->_get_option(); ?>
                            <?php foreach ($option["controls"] as $control_option) {?>
                                <?php $control = $control_option["class"]; ?>
                                <?php $control->_set_option($control_option["option"]);?>
                                <?php $control->_print(); ?>
                            <?php } ?>
                        </div>
                        <div class="modal-footer">
                            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
                        </div>
                    </div>

                </div>
            </div>
        <?php } ?>
    </div>
</body>
</html>
