<div class="makeup-preloader ">
    <ul>
        <li class="gray">
            <span class="top"></span>
            <span class="bottom"></></span>
            <div class="pre-left-bar"><i class="fa fa-picture-o fa-3x" aria-hidden="true"></i></div>
            <div class="pre-right-bar"><i class="fa fa-align-justify fa-3x" aria-hidden="true"></i></div>
        </li>
        <li class="red">
            <span class="top"></span>
            <span class="bottom"></span>
            <div class="pre-left-bar"><i class="fa fa-picture-o fa-3x" aria-hidden="true"></i></div>
            <div class="pre-right-bar"><i class="fa fa-list-ul fa-3x" aria-hidden="true"></i></div>
        </li>
        <li class="black">
            <span class="top"></span>
            <span class="bottom"></></span>
            <div class="pre-left-bar"><i class="fa fa-list-ul fa-3x" aria-hidden="true"></i></div>
            <div class="pre-right-bar"><i class="fa fa-picture-o fa-3x" aria-hidden="true"></i></div>
        </li>
        <li class="blue">
            <span class="top"></span>
            <span class="bottom"></span>
            <div class="pre-left-bar"><i class="fa fa-bars fa-3x" aria-hidden="true"></i></div>
            <div class="pre-right-bar"><i class="fa fa-picture-o fa-3x" aria-hidden="true"></i></div>
        </li>
    </ul>
</div>